version: '1.0'
services:

  # DATABASE

  db:
    image: mysql:5.7
    restart: always
    command: --init-file /data/application/create_database.sql
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - my-db:/var/lib/mysql
      - ./create_database.sql:/data/application/create_database.sql

  # HASIL BUILD KONTAINER
 
  alumni_backend:
    image: alumni_backend
    ports:
      - "80:8000"
    environment:
      - PORT=80
      - CORS_URI=http://localhost:8000/, http://localhost:3010/
      - DB_URI=user:password@tcp(db:3306)/webika?charset=utf8mb4&parseTime=True&loc=Local
      - SECRET_KEY=rahasia
   # DATABASE POOLING  	
      - MAX_OPEN_CONNECTIONS=10
      - MAX_IDLE_CONNECTIONS=2
      - MAX_LIFETIME=60
      - USE_LOGGER=true
      - WKHTMLTOPDF_PATH=/wkhtmltopdf
    depends_on:
      - db

  alumni_frontend:
    image: alumni_frontend
    volumes:
  # CUSTOM CONFIG BUAT TAMBAHIN ROUTE API BACKEND
      - /home/xx/Desktop/cust/xx/Docker/nginx/reverse_proxy.conf:/etc/nginx/conf.d/default.conf
    ports:
      - "80:80"
    environment:
      - PORT=8000
    depends_on:
      - alumni_backend

volumes:
  my-db:
    driver: local